name: Auto AI News Blogger with Gist

on:
  schedule:
    - cron: '0 8 * * *'  # JST 17:00 相当
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SEARCH_API_KEY: ${{ secrets.SEARCH_API_KEY }}
      SEARCH_ENGINE_ID: ${{ secrets.SEARCH_ENGINE_ID }}
      BLOGGER_CLIENT_ID: ${{ secrets.BLOGGER_CLIENT_ID }}
      BLOGGER_CLIENT_SECRET: ${{ secrets.BLOGGER_CLIENT_SECRET }}
      BLOGGER_REFRESH_TOKEN: ${{ secrets.BLOGGER_REFRESH_TOKEN }}
      GIST_ID: ${{ secrets.GIST_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python src/main.py
